### ISSUE TITLE
Socket .connect function is hard coded to connect to ws://localhost:8000/socketcluster/

### ISSUE THREAD

**Issue by heiba** [sacOO7/socketcluster-client-java#1]
Hello,

In your Socket.class, line 347, you have hard coded the class to connect to ws://localhost:8000/socketcluster/ and you're totally ignoring the url which is input in the Socket constructor new Socket(url).

`public void connect() { try {
this.ws = this.factory.createSocket("ws://localhost:8000/socketcluster/");
        } catch (IOException var10) {
            System.out.printf(var10.getMessage(), new Object[0]);
        }`

Please fix

**Comment by sacOO7** [comment]
Hi ,
    I have removed hard-coded URL from Socket.class. You can now download latest dependency jar. Sorry for inconvenience caused. More issues are always welcome :)
