### ISSUE TITLE
can connect to wss (SSL) server

### ISSUE THREAD

**Issue by cogmeta** [sacOO7/socketcluster-client-java#14]
Getting this error 
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
while connecting to wss server. Can this client handle SSL connections? wss://----/socketcluster

**Comment by sacOO7** [comment]
I think you can disable certificate verification?

**Comment by cogmeta** [comment]
Thank you. But disabling certificate verification  is not an option. If missing certificate is the issue, we will add them and try again.

**Comment by sacOO7** [comment]
Yes, you can do that :+1:

**Comment by cogmeta** [comment]
Can we ask for a favor? Can you please try connecting wss://chat.cogmeta.me/socketcluster and let us know. Thanks in advance. I think we are able to connect to ws://chat.cogmeta.me/socketcluster but there is no connect event on server.

**Comment by sacOO7** [comment]
Ohk sure. I think you should test SSL certificate once again.

**Comment by sacOO7** [comment]
And yes do star the client :p .

**Comment by cogmeta** [comment]
We got rid of the ssl certification verification error but we still don't see connect event on server. Can you help us please? Thanks. 

PS: starred the repo.

**Comment by sacOO7** [comment]
Thank you. Can you post your code here. Refer code at this repo. if possible 
https://github.com/sacOO7/LAN-chat-Web-App

**Comment by cogmeta** [comment]
Stepped into Socket.connect and there is OpeningHandshakeException exception:
com.neovisionaries.ws.client.OpeningHandshakeException: The status code of opening handshake response is not '101 switching protocols'. The status line is: HTTP/1.1 400 URL not supported

**Comment by sacOO7** [comment]
What is a URL?

On Sep 17, 2017 1:06 AM, "Cogmeta" <notifications@github.com> wrote:

Stepped into Socket.connect and there is OpeningHandshakeException
exception:
com.neovisionaries.ws.client.OpeningHandshakeException: The status code of
opening handshake response is not '101 switching protocols'. The status
line is: HTTP/1.1 400 URL not supported

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/sacOO7/socketcluster-client-java/issues/14#issuecomment-329990222>,
or mute the thread

**Comment by sacOO7** [comment]
Did you tried my code? I have tested it and it should work without any
problem

**Comment by cogmeta** [comment]
No luck so far in fixing this. URL not supported error. We tried both URLs
wss://subdomain.domain.me/sockercluster and wss://subdomain.domain.me but same error.

Our socketcluster is running behind nginx and it works fine with all browser clients.

/OpenGLRenderer: Initialized EGL, version 1.4
D/AbstractTracker: Event success
I/io.github.sac.Socket: === Status Line ===
I/io.github.sac.Socket: HTTP Version  = 
                        HTTP/1.1
I/io.github.sac.Socket: Status Code   = 
                        400
I/io.github.sac.Socket: Reason Phrase = 
                        URL not supported
I/io.github.sac.Socket: === HTTP Headers ===

**Comment by sacOO7** [comment]
I think cause might be URL. It's little different due to subdomain. Can you
keep domain as www.websitename.com

**Comment by cogmeta** [comment]
We will try and report back. But, it wont really solve our problem as we have multiple socketcluster services running under different subdomains.

**Comment by cogmeta** [comment]
Ok, wss://subdomain.domain.me/sockercluster/  [with trailing slash] works while wss://subdomain.domain.me/sockercluster does not. Most likely it is nginx issue. Will dig deeper and post more. Thanks for your help.
