### ISSUE TITLE
equivalent of send function for sending raw binary data

### ISSUE THREAD

**Issue by cogmeta** [sacOO7/socketcluster-client-java#15]
Is send (or equivalent method) available in android client for sending raw binary data? The web client has _*socket.send*_ method to send binary data which is available in raw event on server. If not, what is the best way to send raw binary data using android client?

**Comment by cogmeta** [comment]
Using base64 encoding to send as string for now. Don't see any noticeable performance de issue due to decoding and encoding...closing for it now.

**Comment by XDex** [comment]
@cogmeta see my fork with binary Socketcluster codecs support: https://github.com/XDex/socketcluster-client-java
