### ISSUE TITLE
How to authenticate connection with Coinigy?

### ISSUE THREAD

**Issue by acz123454** [sacOO7/socketcluster-client-java#17]
Hi, 

As in Title, how should I put 'apiKey' and 'apiSecret' if I want authenticate connection using Yours lib to connect with Coinigy?

Best regards,
Arek

**Comment by sacOO7** [comment]
Hey I think I can point you to the example from where you can replicate for the same?

**Comment by acz123454** [comment]
Hi,

Thanks for Yours answer! :) 

I tried as below:
String url = "wss://sc-02.coinigy.com/socketcluster/";
Socket socket = new Socket(url);

socket.setListener(new BasicListener() {
   public void onConnected(Socket socket, Map<String, List<String>> headers) {
      System.out.println("Connected to endpoint");
   }

   public void onDisconnected(Socket socket, WebSocketFrame serverCloseFrame, WebSocketFrame clientCloseFrame, boolean closedByServer) {
      System.out.println("Disconnected from end-point");
   }

   public void onConnectError(Socket socket, WebSocketException exception) {
      System.out.println("Got connect error " + exception);
   }

   public void onSetAuthToken(String token, Socket socket) {
      socket.setAuthToken(token);
   }

   public void onAuthentication(Socket socket, Boolean status) {
      if (status) {
         System.out.println("socket is authenticated");
      } else {
         System.out.println("Authentication is required (optional)");

         String apiCredentials =
               new Gson().toJson(new ApiCredentials("xxx",
                     "yyy"));

         socket.emit("auth", apiCredentials, new Ack() {
            @Override
            public void call(String name, Object error, Object data) {
               System.out.println("!!");
            }
         });

         Socket.Channel channel = socket.createChannel("zzz");
         channel.subscribe(new Ack() {
            public void call(String channelName, Object error, Object data) {
               if (error == null) {
                  System.out.println("Subscribed to channel " + channelName + " successfully");
               }
            }
         });
      }
   }
});
and 
socket.connect();
Where:
xxx - is my apiKey
yyy - is my secretKey
zzz - private channel ID

Firstly I got call in method “onAuthentication” error info:
	{"errorCode":403,"errorMsg":"Key/Secret Pair Failed”}

Secondly in incoming call in channel.subscribe: 
	Your are connected but this socket has not been authenticated.  Please emit auth event with credentials payload.

Any idea? 

Thanks for all Your answers! :)

Best regards,
Arek

**Comment by acz123454** [comment]
Also ApiCredentials is class as below:
class ApiCredentials {
   String apiKey;
   String apiSecret;

   public ApiCredentials() {
   }

   public ApiCredentials(String apiKey, String apiSecret) {
      this.apiKey = apiKey;
      this.apiSecret = apiSecret;
   }
}

**Comment by acz123454** [comment]
Did method as write below should be automatically called when connect?

public void onSetAuthToken(String token, Socket socket) {
	socket.setAuthToken(token);
}

When I debugging, the method is not called.

**Comment by sacOO7** [comment]
Hey instead of passing API key and value in the form of string, send it as
a json object same as in python.

**Comment by acz123454** [comment]
That is it! :D It works, it was problem in sending String , not Json object :) 

Thanks!

**Comment by sacOO7** [comment]
Ohk I'm closing the issue :). Please star and fork the repo. if you like it :+1: .

**Comment by taomWTP** [comment]
Hi,
I'm using java sample written above and always get exception:

> Got connect error com.neovisionaries.ws.client.WebSocketException: Failed to send an opening handshake request to the server: Received fatal alert: handshake_failure

Does it sample really work now?
