### ISSUE TITLE
Keep getting Error 400 "Reason Phrase = URL not supported" when trying to connect

### ISSUE THREAD

**Issue by heiba** [sacOO7/socketcluster-client-java#2]
Hello,

I have my socketcluster built on kubernetes and rancher, here's the link [sc.qurba.io](sc.qurba.io)

I keep getting error 400 as below:

> 12-05 00:13:37.931 9852-10020/io.qurba.android.debugtool I/System.out: === Status Line ===
> 12-05 00:13:37.932 9852-10020/io.qurba.android.debugtool I/System.out: HTTP Version  = HTTP/1.1
> 12-05 00:13:37.932 9852-10020/io.qurba.android.debugtool I/System.out: Status Code   = 400
> 12-05 00:13:37.932 9852-10020/io.qurba.android.debugtool I/System.out: Reason Phrase = URL not supported
> 12-05 00:13:37.932 9852-10020/io.qurba.android.debugtool I/System.out: === HTTP Headers ===
> 12-05 00:13:37.932 9852-10020/io.qurba.android.debugtool I/System.out: Connection: close

Here's my code trying to connect

`SocketHelper.socket = new Socket("ws://sc.qurba.io/");`

I also tried with the below

`SocketHelper.socket = new Socket("http://sc.qurba.io/");`

**Comment by sacOO7** [comment]
Hey ,this was an easy thing .Sorry , but I should have documented this. When you are trying to connect to soketcluster end-point , by default url is always 'ws://somedomainname.com/socketcluster/' .
So , in your case url must be 'ws://sc.qurba.io/socketcluster/'. I tested with this URL and successfully connected to server.
![screenshot from 2016-12-05 07 47 14](https://cloud.githubusercontent.com/assets/16723785/20871839/a69e0256-babf-11e6-9630-6b46c12f68d0.png)

**Comment by heiba** [comment]
Thanks. Finally got connected.
