### ISSUE TITLE
could you provide jar file with Android Studio compile ?

### ISSUE THREAD

**Issue by xinpengfei520** [sacOO7/socketcluster-client-java#21]
hi,
could you provide jar file with Android Studio compile ?

Thank you!

**Comment by sacOO7** [comment]
Hey why do you need jar file, you can directly add it as a dependency. Sorry for late reply :P .

**Comment by sacOO7** [comment]
Hey do you have any updates on this issue? If not I will close it soon .

**Comment by xinpengfei520** [comment]
ok, thank you very much ! you can close it.
