### ISSUE TITLE
NullPointerException - invoking on null object

### ISSUE THREAD

**Issue by shaunidiot** [sacOO7/socketcluster-client-java#3]
Platform: Android
Library version:
```
compile ('io.github.sac:SocketclusterClientJava:1.7.1'){
  exclude group :'org.json', module: 'json'
}
```

Problem:
On connected, my socket is able to emit and receive messages to and fro the server via internal loggings from the library. However, no callback is actually called to the project's code. 

Example:

Android:
```
socket.setListener(new BasicListener() {
            public void onConnected(Socket socket, Map<String, List<String>> headers) {
                Log.i("Success ", "Connected to endpoint");
                socket.emit("testMessage", "1234");
                socket.on("testMessageBack", new Emitter.AckListener() {
                    @Override
                    public void call(String name, Object data, Ack ack) {
                            Log.e("RESULT", data.toString());
                    }
                });
            }
```

Server:
```
    socket.on('testMessage', function(data) {
      socket.emit('testMessageBack', {
        message: 'This is an object with a message property'
      });
    });
```

Android logs:
```
Message :{"event":"testMessageBack","data":{"message":"This is an object with a message property"}}
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
at io.github.sac.Socket$1.onFrame(Socket.java:185)
at com.neovisionaries.ws.client.ListenerManager.callOnFrame(ListenerManager.java:240)
at com.neovisionaries.ws.client.ReadingThread.callOnFrame(ReadingThread.java:163)
at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:739)
at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:110)
at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:66)
```

It managed to log the results from the server, but my guess is that it's unable to parse them due to some missing data.

Thanks in advance!

**Comment by sacOO7** [comment]
I think you are trying to emit data without having any ack from server side. The correct code to handle this event from client side should be
 
```
socket.on("testMessageBack", new Emitter.Listener() {
            @Override
            public void call(String name, Object data) {
                System.out.println("Event ::"+name+" Data ::"+ data);
            }
        });

```
instead of AckListener

**Comment by shaunidiot** [comment]
Ahh.. I didn't realize that there's another Listener. I always assumed that Android Studio is clever enough to suggest the correct auto-suggest/auto-complete callback part for me. So sorry. My bad!

Also, I realized that you MUST emit a message with the event name. Emitting an event name with an empty String results in the error as well. Is SocketCluster suppose to work like this? Or can something be changed in the library?

Thanks for your help!

**Comment by sacOO7** [comment]
Well, socketcluster is build on event-based architecture. Passing event name as null will obviously violate the base on which framework is built. The client or server are always supposed to communicate through certain event , characterized by its name.

**Comment by shaunidiot** [comment]
I think you may have misread my sentence. I meant emitting the message as empty but having a value for event name. For example:
` 
socket.emit("testMessage", "");
`

Apparently, I've been doing this for months and I probably need to change. Anyhow, thanks for much for your help and your library. Will be closing this for now! Thanks once again! ❤️
