### ISSUE TITLE
 Unauthorized error

### ISSUE THREAD

**Issue by mastani** [sacOO7/socketcluster-client-java#36]
Hello, i'm getting this error when trying to add the library,

> Could not HEAD 'https://jitpack.io/io/github/sac/SocketclusterClientJava/1.7.5/SocketclusterClientJava-1.7.5.pom'. Received status code 401 from server: Unauthorized

Can you help me ?

**Comment by sacOO7** [comment]
Try 1.7.4 for now. I will look into the issue

**Comment by mastani** [comment]
Thanks for fast answer!
But for 1.7.4 i get the same error.

> Could not HEAD 'https://jitpack.io/io/github/sac/SocketclusterClientJava/1.7.4/SocketclusterClientJava-1.7.4.pom'. Received status code 401 from server: Unauthorized

**Comment by sacOO7** [comment]
How are you exactly adding library as a dependency in your project?

**Comment by mastani** [comment]
Same as you describe in readme,

`compile ('io.github.sac:SocketclusterClientJava:1.7.4') {
      exclude group: 'org.json', module: 'json'
}`

Actually I use your library for a month now and it was ok until now.

**Comment by sacOO7** [comment]
Idk what caused this problem..... I might need to reproduce it on my local

**Comment by mastani** [comment]
Maybe it's because you change maven settings to private ?

**Comment by sacOO7** [comment]
Ok I will look into it

**Comment by sacOO7** [comment]
Can you check this https://jfrog.com/knowledge-base/why-am-i-failing-to-work-with-jfrog-saas-service-with-tls-1-0-1-1/

**Comment by sacOO7** [comment]
You can find my maven published artifacts here https://dl.bintray.com/sacoo7/Maven/
It's a public link and I don't think it will require authentication.

**Comment by mastani** [comment]
I checked the link you provided, But my Android Studio is up-to-date. I don't think it's the cause of my problem. I added jar files manually to libs/ folder for now and it's working.

**Comment by sacOO7** [comment]
I will try to fix it today ...

**Comment by mastani** [comment]
Thank you, and thanks for your awesome project by the way.

**Comment by sacOO7** [comment]
Hi @mastani , I tried yesterday to add latest version as a dependency in gradle, but it is working for me. Can you please check it again? Maybe on build pipeline or on your friends laptop?

**Comment by sacOO7** [comment]
Still I will add public artifact link in the README. Please let me know about above...

**Comment by mastani** [comment]
It is working now, checked for 1.7.4 and 1.7.5.
I tried just now and it's fine.

Thanks for your time!

**Comment by sacOO7** [comment]
Ok, then I will be closing this issue .....

**Comment by hosseinhelali** [comment]
Hi I am getting this error when trying to add library too

`authentication failed for https://repo.spring.io/plugins-release/io/github/sac/SocketclusterClientJava/1.7.4/SocketclusterClientJava-1.7.4.pom, status: 401 Unauthorized`

Maven dependency:

```
		<dependency>
			<groupId>io.github.sac</groupId>
			<artifactId>SocketclusterClientJava</artifactId>
			<version>1.7.5</version>
		</dependency>
```

**Comment by zsquare777** [comment]
> I checked the link you provided, But my Android Studio is up-to-date. I don't think it's the cause of my problem. I added jar files manually to libs/ folder for now and it's working.

can i have this jar file? I searched everywhere for pom, arr or jar but didn't found any luck. Can you please share jar file?


> Thank you, and thanks for your awesome project by the way.

**Comment by mastani** [comment]
> > I checked the link you provided, But my Android Studio is up-to-date. I don't think it's the cause of my problem. I added jar files manually to libs/ folder for now and it's working.
> 
> can i have this jar file? I searched everywhere for pom, arr or jar but didn't found any luck. Can you please share jar file?
> 
> 
> > Thank you, and thanks for your awesome project by the way.
> 
> 

Sorry i don't have it anymore, it was 6 years ago ...
