### ISSUE TITLE
auth before connect to socket connection

### ISSUE THREAD

**Issue by miladr0** [sacOO7/socketcluster-client-java#38]
hi
in socket.io i use this way for auth before connect to socket.

`IO.Options options = new IO.Options();
            options.query = "token=" + token;
            socket = IO.socket(SERVER_ADDRESS, options);
           socket.connect();
`
can i user this way with this library?

**Comment by sacOO7** [comment]
You can use setAuthToken method on the socket to set token, before
connecting to server.

**Comment by sacOO7** [comment]
Hi @miladr0 , will close the issue, if your problem is resolved 👍

**Comment by miladr0** [comment]
hi @sacOO7 , i couldn't solved the problem according to your suggestion, so i stick to socket.io, thanks anyway.

**Comment by sacOO7** [comment]
Ohh no problem @miladr0 , please let me know if you use socketcluster in future and face any problem again 👍.

**Comment by AnkitPat** [comment]
hello @sacOO7 

How to set multiple option in your library.

I have option like this:

{
  hostname: 'chat.xxx.com',
  secure: true,
  port: 5001,
  rejectUnauthorized: false // Only necessary during debug if using a self-signed certificate
}
