### ISSUE TITLE
Project should has .gitignore file

### ISSUE THREAD

**Issue by zain-saqer** [sacOO7/socketcluster-client-java#4]
The project should has .gitignore file, for git to ignore generated files, .class files and idea files.
See this https://gist.github.com/chrisjenx/6138781

**Comment by sacOO7** [comment]
I think that will not be causing major problem for now, will add it next time when I push the project.

**Comment by zain-saqer** [comment]
I can do this task. What do you think?

**Comment by sacOO7** [comment]
Ok, wait. why do you want to do this. Tell me what problem you are facing right now?

**Comment by zain-saqer** [comment]
Currently nothing, I just cloned this project. If I encounter any problem I will report here.
