### ISSUE TITLE
Change status to authenticated when reciveing #setAuthToken or #removeAuthToken events

### ISSUE THREAD

**Issue by zain-saqer** [sacOO7/socketcluster-client-java#5]
Library should has authentication status. and change this status when server send `#setAuthToken` or `#removeAuthToken` events. And `BasicListener`'s `OnAuthentication` should be fired whenever authentication status change.
Check socketcluster-client library implementation https://github.com/SocketCluster/socketcluster-client/blob/master/lib/scsocket.js#L183

**Comment by sacOO7** [comment]
I think you get auth status in callback.Try sending proper auth data from server and authentication callbacks will handle everything for you.

**Comment by zain-saqer** [comment]
I send `login` event to sever, server authenticated on the server, and server send `#setAuthToken` event. Here the client should set the new token and fire `BasicListener`'s `OnAuthentication` event, because I'm authenticated now (right?). but OnAuthentication callback is only called after connect.

**Comment by sacOO7** [comment]
When setAuthToken method is called ,it means that you got authenticated token and you are authenticated. Next time you send token to server, server will verify it and then authenticated callback will be executed.It won't execute on setAuthToken.

**Comment by sacOO7** [comment]
I'm closing this issue for now, as I can't see any significant problem.
