### ISSUE TITLE
WebSocket sendText on a null object reference

### ISSUE THREAD

**Issue by vtn1508** [sacOO7/socketcluster-client-java#52]
![Capture](https://user-images.githubusercontent.com/57479477/71456359-a3e8aa80-27cb-11ea-8be1-c695fd8e25ac.PNG)

Sorry because of my English 
My app was crashed only  in the **first times** install app because of this bug But after that it's run normally
And i don't use com.neovisionaries.ws.client.WebSocket.sendText anywhere
Please help me  !

**Comment by sachinsh76** [comment]
Why did u close it?
