### ISSUE TITLE
Working with self signed ceritificate HTTPs

### ISSUE THREAD

**Issue by bv99** [sacOO7/socketcluster-client-java#7]
Hi, greate project you made there, thank you
So I get some problem here, can we use self signed sertificate here in this project? Thank you for your help

**Comment by sacOO7** [comment]
I think I have documented everything, try following before setting connection to server
https://github.com/sacOO7/socketcluster-client-java#handling-ssl-connection-with-server

**Comment by bv99** [comment]
Thanks it is works by now, sory I am new in android coding,
In case someone need help like me,I managed it to work by implementing context in this [https://developer.android.com/training/articles/security-ssl.html#ClientCert] to `factory.setSSLContext(context);` in the link @sacOO7  provide
