### ISSUE TITLE
SocketCluster Android Client Can't Receive message on 'message' event

### ISSUE THREAD

**Issue by jodyhuang** [sacOO7/socketcluster-client-java#8]
I have a nodejs server base on SocketCluster.
My issue is: From Android Client (base on https://github.com/sacOO7/socketcluster-client-java),
I can send message to server successfully, but I can’t receive the message from server(socket.send(msgStr))
on message event. Some of  android code as follows:
scSocket.on("message", new io.github.sac.Emitter.Listener() {
    public void call(String eventName,Object object) {
        // Cast object to its proper datatype
        System.out.println("Got message for :"+eventName+" data is :"+data);
    }
});
Can you give me some suggest, thanks.

**Comment by sacOO7** [comment]
Can I ask which version of library you are using right now? I can help if you put down your server and client side code for handling events.
